<?php
// File: /devbot/devbot.php

require_once(__DIR__ . '/devbot_config.php');

$mysqli = new mysqli($db_host, $db_user, $db_pass, $db_name);
if ($mysqli->connect_error) {
    file_put_contents($log_dir . '/devbot_proc.log', "[" . date('c') . "] DB connection failed: " . $mysqli->connect_error . "\n", FILE_APPEND);
    exit;
}

$today = date('Y-m-d');
$slug = 'devlog-' . strtolower(date('F-j-Y'));
$title = "Development Log – " . date('F j, Y');
$intro = "Automated devlog for " . date('l, F j, Y') . " generated by DevBot.";
$todays_logs = [];

file_put_contents($log_dir . '/devbot_debug.log', "[" . date('c') . "] devbot initiated\n", FILE_APPEND);

// Load core log files
$logs = glob($log_dir . '/*.log');
foreach ($logs as $file) {
    $mtime = filemtime($file);
    if (date('Y-m-d', $mtime) === $today) {
        $content = file_get_contents($file);
        $todays_logs[] = "?? Log File: " . basename($file) . "\n\n" . $content;
    }
}

// Explicitly check error_log
$explicit_error_log = dirname(__DIR__, 2) . '/error_log';
if (file_exists($explicit_error_log)) {
    $lines = file($explicit_error_log);
    $today_errors = [];
    foreach ($lines as $line) {
        if (strpos($line, $today) !== false) {
            $today_errors[] = $line;
        }
    }
    if (!empty($today_errors)) {
        $todays_logs[] = "? PHP Errors Today (error_log):\n\n" . implode("", $today_errors);
    }
}

// ?? Load plugins from /plugins directory
$plugin_files = glob(__DIR__ . '/plugins/*.php');
foreach ($plugin_files as $plugin) {
    try {
        include_once $plugin; // plugins push to $todays_logs[]
    } catch (Throwable $t) {
        file_put_contents($log_dir . '/devbot_debug.log', "[" . date('c') . "] Plugin error in $plugin: " . $t->getMessage() . "\n", FILE_APPEND);
    }
}

// Bail if nothing found
if (empty($todays_logs)) {
    file_put_contents($log_dir . '/devbot_proc.log', "[" . date('c') . "] No new logs.\n", FILE_APPEND);
    exit;
}

// Build content
$content = "<pre>" . htmlspecialchars(implode("\n\n---\n\n", $todays_logs)) . "</pre>";

// Check if today's post exists
$existing_id = null;
$check = $mysqli->prepare("SELECT id FROM posts WHERE post_slug = ?");
$check->bind_param("s", $slug);
$check->execute();
$check->bind_result($existing_id);
$check->fetch();
$check->close();

if ($existing_id) {
    $stmt = $mysqli->prepare("UPDATE posts SET content = CONCAT(content, ?), updated_at = NOW() WHERE id = ?");
    $stmt->bind_param("si", $content, $existing_id);
    $stmt->execute();
    file_put_contents($log_dir . '/devbot_proc.log', "[" . date('c') . "] Devlog updated: $slug\n", FILE_APPEND);
    $stmt->close();
} else {
    $stmt = $mysqli->prepare("INSERT INTO posts (title, post_slug, intro, content, user_id, is_published) VALUES (?, ?, ?, ?, ?, 1)");
    $stmt->bind_param("ssssi", $title, $slug, $intro, $content, $admin_id);
    $stmt->execute();
    file_put_contents($log_dir . '/devbot_proc.log', "[" . date('c') . "] Devlog posted: $slug\n", FILE_APPEND);
    $stmt->close();
}

$mysqli->close();
